### ISSUE TITLE
Doxygen Docs Missing

### ISSUE THREAD

**Issue by blaskovicz** [adafruit/Adafruit_IO_Arduino#116]
On the main page of the doxygen docs, I see no available classes, docs, etc, only the doxygen header.

http://adafruit.github.io/Adafruit_IO_Arduino/html/index.html

**Comment by siddacious** [comment]
Strange! I'll take a look, thanks for the heads up

**Comment by brentru** [comment]
@siddacious  

Looks like the Action says it's uploading code.. https://github.com/adafruit/Adafruit_IO_Arduino/runs/618318416?check_suite_focus=true#step:7:13

but the `GH-Pages` branch looks like it hasn't been updated by actions since Jan: https://github.com/adafruit/Adafruit_IO_Arduino/tree/gh-pages

Maybe this occurred when we switched from travis->actions?

**Comment by siddacious** [comment]
@brentru I just tested and found that what's up is representative of what Doxygen is currently generating. I started a branch here:
https://github.com/adafruit/Adafruit_IO_Arduino/tree/docs_fix

If you can, please look into what's happening. Assign this back to me if you need me to take over.

**Comment by andrewwatson** [comment]
was just about to submit an issue for this but it's already here!

**Comment by siddacious** [comment]
@brentru Have you been able to take a look at this?

**Comment by brentru** [comment]
@siddacious  No, I haven't looked at it yet. I can take a closer look at it on Friday this week.
