### ISSUE TITLE
will there be Pi Pico W support?

### ISSUE THREAD

**Issue by DanielGernert** [adafruit/Adafruit_IO_Arduino#157]
Hey guys, do you plan to add the Pi Pico W to the list of supported boards?
I saw some posts about using it woth MicroPython but  would love to use the board with it's Arduino integration:
https://github.com/earlephilhower/arduino-pico

**Comment by brentru** [comment]
There are no current plans/ETA for this library. It will likely get added once we add it into the Adafruit.IO WipperSnapper library first (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/280). You may want to subscribe that issue for updates!

**Comment by nledevil** [comment]
Now that Pico W support has been rolled into the Adafruit_Wippersnapper_Arduino library, can we get Pico W support for the Adafruit_IO_Arduino library?

**Comment by lcoffin** [comment]
Is the Pico W similar enough to the Arduino Nano RP2040 Connect? I'm using the Connect with the MKR1010 configuration in Adafruit_IO_Arduino library and it seems to work ok. (I'm getting a lot of errors/issues, but I think they are mostly caused by my trying to manage WiFi separately - outside the ArduinoIO library.) Or is it that the Pico W has a different WiFi module that would keep it from working the same?
