### ISSUE TITLE
ESP8266 Floating Point

### ISSUE THREAD

**Issue by JacqueDouglas** [adafruit/Adafruit_IO_Arduino#3]
There seems to be a problem sending floating point numbers with the ESP8266.

**Comment by pmcdonaldgit** [comment]
Ya I am reporting the same problem. Floats and doubles can not be sent with Adafruit_IO_Feed.send(float) because the library functions for sprintf don't work with floats. 

There is some note about how to turn on support for them in the standard libaries, but given the simplicty it would be nice if we could get a version of the libary that just handles the couple of instances where it is passing floats/doubles without needing to enable floating point in the libaries.

There is already a conditional in the two (float/double) send functions to use an alternate conversion to snprintf, but it isn't appropriate for the ESP. Need an additional conditional or manual conversion in the library... PLEASE.

**Comment by tdicola** [comment]
Oh no problem, yeah it's unfortunate but it looks like the ESP8266 Arduino library doesn't implement all the same double to string functions as avrlibc hence the fallback to snprintf.  However it looks like at least dtostrf is there so it's good enough to put in a special case.  Just committed a fix--grab the latest code and it should send floats & doubles without issue.  

One side effect though is that since they only have dtostrf and not dtostre (scientific notation) I had to make a judgement call on how many decimal places of precision to use by default when sending floats/doubles.  I picked 6 but you can override it by passing a second parameter to send.  This is an int that sets the precision (digits after the decimal point) for dtostrf.  The buffer it uses can hold up to ~40 characters to you can go pretty crazy and hit the max float value in theory.

Thanks for raising the issue and apologies it took a little while to get to!
